"""Superlatives table

Revision ID: 4c819855bc5d
Revises: 13ee552dc345
Create Date: 2020-08-31 15:05:55.445973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c819855bc5d'
down_revision = '13ee552dc345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superlatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('example', sa.String(length=120), nullable=False),
    sa.Column('ss1', sa.String(length=120), nullable=False),
    sa.Column('ss2', sa.String(length=120), nullable=False),
    sa.Column('ss3', sa.String(length=120), nullable=False),
    sa.Column('comment', sa.String(length=120), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('added_when', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superlatives')
    # ### end Alembic commands ###
