"""empty message

Revision ID: 7757e235126f
Revises: 
Create Date: 2020-09-05 23:31:58.909575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7757e235126f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('added_when', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('updated_when', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brandname', sa.String(length=120), nullable=False),
    sa.Column('abbreviation', sa.String(length=120), nullable=True),
    sa.Column('ss1', sa.String(length=120), nullable=True),
    sa.Column('ss2', sa.String(length=120), nullable=True),
    sa.Column('ss3', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_when', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brandname')
    )
    op.create_table('superlatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('example', sa.String(length=120), nullable=True),
    sa.Column('ss1', sa.String(length=120), nullable=True),
    sa.Column('ss2', sa.String(length=120), nullable=True),
    sa.Column('ss3', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_when', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('uom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('ss1', sa.String(length=120), nullable=True),
    sa.Column('ss2', sa.String(length=120), nullable=True),
    sa.Column('ss3', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_when', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptpt', sa.String(length=120), nullable=False),
    sa.Column('ptbr', sa.String(length=120), nullable=False),
    sa.Column('abbreviation', sa.String(length=120), nullable=True),
    sa.Column('ss1', sa.String(length=120), nullable=True),
    sa.Column('ss2', sa.String(length=120), nullable=True),
    sa.Column('ss3', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_when', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ptbr'),
    sa.UniqueConstraint('ptpt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('uom')
    op.drop_table('superlatives')
    op.drop_table('brands')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('grocery')
    # ### end Alembic commands ###
