"""empty message

Revision ID: ba7e0479e077
Revises: 7757e235126f
Create Date: 2020-09-06 15:10:16.108209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7e0479e077'
down_revision = '7757e235126f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prohibited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('example', sa.String(length=120), nullable=True),
    sa.Column('ss1', sa.String(length=120), nullable=True),
    sa.Column('ss2', sa.String(length=120), nullable=True),
    sa.Column('ss3', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_when', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prohibited')
    # ### end Alembic commands ###
